"""
Synaptum — framework de agentes y runtime durable, agnóstico al proveedor.

Es dueño de la *semántica* de ejecución: qué es un paso, dónde puede cortarse,
qué puede repetirse y cómo se re-deriva el contexto.  El *sustrato* — dónde se
persiste, con qué retención y bajo qué política — pertenece al harness.

Estado: v1.0 en construcción.  Fase 0 (contratos) en curso; ver ``roadmap.md``.
"""

from .core import (
    ALLOW,
    SEAM_VERSION,
    SUPPORT_WINDOW,
    AbortError,
    CallContext,
    Checkpointer,
    ConfigurationError,
    Denied,
    Gateway,
    Hello,
    InvalidToolCallError,
    LimitExceeded,
    NetworkError,
    NoObjectGeneratedError,
    ProviderError,
    RequestTimeoutError,
    RunState,
    SeamVersionError,
    SynaptumError,
    ToolExecutionError,
    Welcome,
    negotiate,
    retryable_for_status,
    supported_versions,
    AUTO,
    ApprovalStep,
    Audio,
    ContentPart,
    Decision,
    DelegateStep,
    Disposition,
    Document,
    Durability,
    Event,
    FinalStep,
    Finish,
    FinishReason,
    Image,
    Message,
    ModelStep,
    Phase,
    ReasoningDelta,
    ReasoningEnd,
    ReasoningStart,
    RedactedThinking,
    Request,
    Response,
    ResponseFormat,
    Risk,
    Role,
    StepEvent,
    StreamEvent,
    StreamStart,
    Text,
    TextDelta,
    TextEnd,
    TextStart,
    Thinking,
    ToolCall,
    ToolCallDelta,
    ToolCallEnd,
    ToolCallStart,
    ToolChoice,
    ToolDefinition,
    ToolResult,
    ToolStep,
    Usage,
    b64,
    dumps,
    idempotency_key,
    make_step_id,
    to_jsonable,
)
from .core import UncertainEffect
from .core import __all__ as _core_all
from .agent import Agent, Limits, Session
from .run import (
    Check,
    HttpModel,
    Journal,
    LocalGateway,
    MemoryCheckpointer,
    Replay,
    SqliteCheckpointer,
)
from .prompts import (
    FilePrompts,
    InMemoryPrompts,
    PromptProvider,
    PromptRegistry,
    PromptTemplate,
    fmt_dict,
    fmt_list,
    fmt_records,
)
from .providers import Provider
from .schema import Schema, schema_for
from .tools import Tool, json_schema_for, tool

__version__ = "1.0.0rc1"
__all__ = [
    *_core_all,      # ya trae UncertainEffect: repetirlo aquí lo duplicaba
    "Agent",
    "Limits",
    "Session",
    "Journal",
    "MemoryCheckpointer",
    "Replay",
    "SqliteCheckpointer",
    "HttpModel",
    "LocalGateway",
    "Check",
    "Tool",
    "tool",
    "json_schema_for",
    "Provider",
    "PromptTemplate",
    "PromptProvider",
    "InMemoryPrompts",
    "FilePrompts",
    "PromptRegistry",
    "fmt_dict",
    "fmt_list",
    "fmt_records",
    "Schema",
    "schema_for",
    "__version__",
]
